jobs:
  - job:
    templateContext:
      outputs:
        - output: nuget
          packagesToPush: "$(Build.ArtifactStagingDirectory)/*.nupkg"
          packageParentPath: "$(Build.ArtifactStagingDirectory)"
          nuGetFeedType: internal
          publishVstsFeed: "e6a70c92-4128-439f-8012-382fe78d6396/c0493cce-bc63-4e11-9fc9-e7c45291f151"
          sbomPackageName: "Azure Functions PowerShell Worker"
          sbomBuildComponentPath: "$(Build.SourcesDirectory)"
          allowPackageConflicts: true
        # - output: nuget
        #   condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'), eq(variables['UPLOADPACKAGETOPRERELEASEFEED'], true))
        #   packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        #   packageParentPath: '$(Build.ArtifactStagingDirectory)'
        #   nuGetFeedType: 'internal'
        #   publishVstsFeed: 'e6a70c92-4128-439f-8012-382fe78d6396/f37f760c-aebd-443e-9714-ce725cd427df' # AzureFunctionsPreRelease feed
        #   allowPackageConflicts: true
    steps:
      - pwsh: ./build.ps1 -NoBuild -Bootstrap
        displayName: "Running ./build.ps1 -NoBuild -Bootstrap"

      - pwsh: |
          $ErrorActionPreference = "Stop"

          ./build.ps1 -Clean -Configuration Release -BuildNumber "$(buildNumber)"
        displayName: "Build worker code"

      - task: CopyFiles@2
        inputs:
          SourceFolder: "$(System.DefaultWorkingDirectory)/package"
          Contents: |
            **/*.nuspec
            **/*.nupkg
          TargetFolder: "$(Build.ArtifactStagingDirectory)"
          flattenFolders: true
        displayName: "Copy package to artifacts directory"
