jobs:
  - job: UnitTests
    steps:
      - pwsh: ./build.ps1 -NoBuild -Bootstrap
        displayName: "Running ./build.ps1 -NoBuild -Bootstrap"

      - pwsh: ./Check-CsprojVulnerabilities.ps1
        displayName: "Check for security vulnerabilities"

      - pwsh: |
          $ErrorActionPreference = "Stop"

          ./build.ps1 -Clean -Configuration Release
        displayName: "Build worker code"

      - pwsh: ./build.ps1 -NoBuild -Test
        displayName: "Running UnitTest"

      # - pwsh: ./test/E2E/Start-E2ETest.ps1
      #   env:
      #     AzureWebJobsStorage: $(AzureWebJobsStorage)
      #     AzureWebJobsCosmosDBConnectionString: $(AzureWebJobsCosmosDBConnectionString)
      #     AzureWebJobsServiceBus: $(AzureWebJobsServiceBus)
      #     AzureWebJobsEventHubSender: $(AzureWebJobsEventHubSender)
      #     FUNCTIONS_WORKER_RUNTIME: "powershell"
      #   displayName: "Running E2ETest"

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: "VSTest"
          testResultsFiles: "**/*.trx"
          failTaskOnFailedTests: true
        condition: succeededOrFailed()
        displayName: "Publish tests results"
