parameters:
  - name: IsPrerelease
    type: boolean
    default: true

trigger:
  batch: true
  branches:
    include:
      - v4.x/*
      - v3.x/*

# CI only, does not trigger on PRs.
pr: none

resources:
  repositories:
    - repository: 1es
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

variables:
  Configuration: Release
  buildNumber: $[ counter('build', 4000) ] # Start higher than our AppVeyor versions. Every build (pr or branch) will increment.

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows

    stages:
      - stage: WindowsUnitTests
        dependsOn: []
        jobs:
          - template: /eng/ci/templates/test.yml@self

      - stage: LinuxUnitTests
        dependsOn: []
        jobs:
          - template: /eng/ci/templates/test.yml@self
        pool:
          name: 1es-pool-azfunc
          image: 1es-ubuntu-22.04
          os: linux

      - stage: Build
        dependsOn: [WindowsUnitTests, LinuxUnitTests]
        jobs:
          - template: /eng/ci/templates/build.yml@self
            parameters:
              IsPrerelease: ${{ parameters.IsPrerelease }}
