trigger:
  batch: true
  branches:
    include:
    - dev
    - v4.x/*
    - v3.x/*

resources:
  repositories:
    - repository: 1es
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows

    stages:
      - stage: WindowsUnitTests
        dependsOn: []
        jobs:
          - template: /eng/ci/templates/test.yml@self
        pool:
          name: 1es-pool-azfunc-public

      - stage: LinuxUnitTests
        dependsOn: []
        jobs:
          - template: /eng/ci/templates/test.yml@self
        pool:
          name: 1es-pool-azfunc-public
          image: 1es-ubuntu-22.04
          os: linux
